<<<<<<< HEAD
// This file generated by sqlaction v0.2.7.0
=======
// This file generated by sqlaction v0.2.1.0
>>>>>>> 52a90cb5db91f8e546c7fdeb10a805d9ad9bb567

package xyz.calvinwilliams.sqlaction;

import java.math.*;
import java.util.*;
import java.sql.Time;
import java.sql.Timestamp;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

<<<<<<< HEAD
public class SqlactionDemoSAU extends SqlactionDemoSAO {
=======
public class SqlactionDemoSAU {
>>>>>>> 52a90cb5db91f8e546c7fdeb10a805d9ad9bb567

}
